default:
  navigation:
    - title: Экстрим
      subtitle: Пощекотать нервы
      url: /t/attractions/ekstrim
      items:
        - :title: Мертвая петля
          :url: /t/attractions/ekstrim/miertvaia-pietlia
        - :title: Душа в пятки
          :url: /t/attractions/ekstrim/dusha-v-piatki
        - :title: Я Гагарин
          :url: /t/attractions/ekstrim/ia-gagarin
      promo_banners:
        - subtitle: Новые аттракционы
          title: Осень 2020
          url: /t/ekstrim
          image: 'meganav/parkoved_promo_banner_left-first-category.jpg'
        - subtitle: Специальные предложения
          title: Получи скидку до 30% 
          url: /t/attractions/ekstrim
          image: 'meganav/parkoved_promo_banner_right-first-category.jpg'
    - title: Семейные
      subtitle: Развлечения
      url: /t/attractions/family
      items:
        - :title: Карусели
          :url: /t/attractions/family/carousel
        - :title: Колесо оборзения
          :url: /t/attractions/view_wheel
        - :title: Тиры
          :url: /t/attractions/family/shooter
      promo_banners:
        - subtitle: Живые клоуны
          title: Зима 2020-21
          url: /t/attractions/family
          image: 'meganav/parkoved_promo_banner_left-first-category.jpg'
        - subtitle: Специальное предложение
          title: Катание на верблюдах
          url: /t/attractions/family
          image: 'meganav/parkoved_promo_banner_right-first-category.jpg'
    - title: Детские
      subtitle: Нашкодим !
      url: /t/attractions/kids
      items:
        - :title: Заколдованный лес
          :url: /t/attractions/kids/magic_wood
        - :title: Бег в мешках
          :url: /t/attractions/kids/bags_running
        - :title: Морское царство
          :url: /t/attractions/kids/sea_world
      promo_banners:
        - subtitle: Родельбан
          title: Осень-Зима 2020-21
          url: /t/attractions/kids
          image: 'meganav/parkoved_promo_banner_left-first-category.jpg'
        - subtitle: Специальное предложение
          title: Безумные скидки
          url: /t/attractions/kids
          image: 'meganav/parkoved_promo_banner_right-first-category.jpg'
